pipeline {
    agent any
    environment {
        PATH = "$PATH:/usr/local/bin/"
        // Git repository URL
        GIT_REPO_URL = "https://github.com/Sachinn-9700/Auto-scaling-ecommerce-devops.git"
        // Docker Hub credentials
        DOCKER_HUB_TOKEN = credentials("docker_hub_token")
        // Docker image name
        BACKEND_IMAGE = "ecommerce-backend"
        FRONTEND_IMAGE = "ecommerce-frontend"
        TAG = "v1"
    }
    stages {
        steps ("checkout") {
            // Checkout the code from the Git repository
            git url: "${GIT_REPO_URL}"
        }
    }
    stages ("build backend image") {
        steps {
            script {
                sh "docker image build -t \"${BACKEND_IMAGE}:${TAG}\" ."
            }
        }
    }
    stage ("build frontend image") {
        steps {
            script {
               sh "docker image build -t \"${FRONTEND_IMAGE}:${TAG}\" ./frontend"
            }
        }
    }
    stage('Docker Hub Login') {
            steps {
                echo 'Logging in to Docker Hub'
                 sh 'echo "$DOCKER_HUB_TOKEN" | docker login -u sachinn9700 --password-stdin'
                 }
    }
    stage('Push Backend Image') {
        steps {
            echo 'Pushing Backend Image to Docker Hub'
            sh "docker push ${BACKEND_IMAGE}:${TAG}"
        }
    }
    stage('Push Frontend Image') {
        steps {
            echo 'Pushing Frontend Image to Docker Hub'
            sh "docker push ${FRONTEND_IMAGE}:${TAG}"
        }
    }
    stage ("Deploy to Kubernetes") {
        steps {
            sh"""
            kubectl apply -f k8s/namespace.yaml
            kubectl apply -f k8s/
            """
        }
    }
    post {
        success {
            echo "CI/CD Pipeline Completed Successfully"
        }
        failure {
            echo "Pipeline Failed"
        }
    }
}
